<?php

namespace NotORM;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-21 at 23:07:18.
 */
class LiteralTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Literal
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Literal;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers NotORM\Literal::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
