language: php

php:
  - 5.4
  - 5.5  
  - 5.6
  - 7.0

services:
  - memcached

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# try running against postgres 9.3
addons:
  postgresql: "9.3"

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  - travis_retry composer install --prefer-dist --no-interaction
  - tests/travis/apc-setup.sh
  - tests/travis/memcache-setup.sh

before_script:
  - mysql --version
  - psql --version
  # initialize databases
  - mysql -e 'CREATE DATABASE software;';
  - psql -U postgres -c 'CREATE DATABASE software;';

  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

script:
  - phpunit --verbose $PHPUNIT_FLAGS --exclude-group pgsql

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
